services:
  mysql:
    image: mysql:8.4
    container_name: campus-food-mysql
    environment:
      MYSQL_DATABASE: campus_food
      MYSQL_USER: campus
      MYSQL_PASSWORD: campus
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.4
    container_name: campus-food-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: campus-food-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mysql_data:

